sudo: false
language: node_js
cache:
  directories:
    - node_modules
node_js:
  - "0.10.43"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
before_install:
  - curl https://install.meteor.com | /bin/sh
  - export PATH="$HOME/.meteor:$PATH"
  - npm install -g gulp-cli
install:
  - meteor npm install
script:
  - gulp test
  - meteor remove practicalmeteor:mocha
  - meteor add dispatch:mocha-phantomjs
  - meteor test --once --driver-package=dispatch:mocha-phantomjs
