topogram:
  image: topogram/topogram
  ports:
   - "8080:8080"
  links:
   - mongo
  environment:
   - MONGO_URL=mongodb://mongo:27017/yourapp # "mongo:27017" resolves to the internal IP of the container below
   - ROOT_URL=http://localhost
   - MAIL_URL=smtp://some.mailserver.com:25

mongo:
  image: mongo:latest
  ports:
  - "27016:27017"
